import type { Metadata } from "next";
import { Geist, Oxygen, Poppins } from "next/font/google";
import "./globals.css";
import HomeHeader from "./components/common/home_header";
import HomeFooter from "./components/common/home_footer";
import Providers from "../providers";
import Header from "./components/common/header_exp";

const poppins_font = Oxygen({
  variable: "--font-oxygen",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "700"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "GMP App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins_font.variable} ${poppins_font.variable}`}
      >
        <Providers>
          {/* <HomeHeader /> */}
          <Header />
          {children}
          <HomeFooter />
        </Providers>
      </body>
    </html>
  );
}
