import type { Metadata } from "next";
import BasicAppShell from "./components/baseappshell";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <BasicAppShell> */}
          {children}
        {/* </BasicAppShell> */}
      </body>
    </html>
  );
}
