import type { Metadata } from "next";
import BasicAppShell from "./components/baseappshell";
import Providers from "../providers";
import NextTopLoader from 'nextjs-toploader';
import { ToastContainer } from 'react-toastify';
import './globals.css';



export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Providers>
          <ToastContainer />
          <NextTopLoader
            color={"#EE0202"}
            template='<div class="bar" role="bar"><div class="peg"></div></div>'
          />
          <BasicAppShell>
            {children}
          </BasicAppShell>
        </Providers>
      </body>
    </html>
  );
}
