import type { Metadata } from "next";
import BasicAppShell from "./components/baseappshell";
import Providers from "../providers";
import NextTopLoader from 'nextjs-toploader';
import './globals.css';
import AutoLayoutClient from "./components/AutoLogoutClient";



export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <AutoLayoutClient /> */}
        <NextTopLoader
                color={"#EE0202"}
                template='<div class="bar" role="bar"><div class="peg"></div></div>'
            />
          <BasicAppShell>
            {children}
          </BasicAppShell>
        </Providers>
      </body>
    </html>
  );
}
